// <auto-generated by="the Blazor I18n Text compiler" />
namespace SampleSite.I18nText.Layout
{
    public partial class Localize : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash.Hash => "s3y4lo7d9s";

        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Source Code"</summary>
        public string Source_Code;

        /// <summary>"&quot;Blazor File Drop Zone&quot; demonstration site"</summary>
        public string Title;
    }
}
