// <auto-generated by="the Blazor I18n Text compiler" />
namespace SampleSite.I18nText.UploadCompleted
{
    public partial class Localize : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"BACK TO HOME"</summary>
        public string BACK_TO_HOME;

        /// <summary>"Upload was completed."</summary>
        public string Upload_was_completed;
    }
}
