// <auto-generated by="the Blazor I18n Text compiler" />
namespace SampleSite.I18nText.UploadAvatorPicture
{
    public partial class Localize : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Avatar picture file"</summary>
        public string Avatar_picture_file;

        /// <summary>"Choose File"</summary>
        public string Choose_File;

        /// <summary>"Chosed file is not picture."</summary>
        public string Chosed_file_is_not_picture;

        /// <summary>"Chosed file is too large."</summary>
        public string Chosed_file_is_too_large;

        /// <summary>"Max allowed file size is 512KB."</summary>
        public string Max_allowed_file_size_is_512KB;

        /// <summary>"No file chosen"</summary>
        public string No_file_chosen;

        /// <summary>"Chose or &lt;b&gt;drag &amp;amp; drop&lt;/b&gt; your avatar picture file and upload it."</summary>
        public string Please_upload_your_avator_picture;

        /// <summary>"Success!"</summary>
        public string Success;

        /// <summary>"Upload"</summary>
        public string Upload;
    }
}
